### ISSUE TITLE
removeInvalidatedBisacCodes(): Argument #2 ($book_information_array) must be of type array, bool given

### ISSUE THREAD

**Issue by SylDanh** [pressbooks/pressbooks#3285]
### Description

On page "book info" i got this message  
![Screenshot 2023-04-20 at 11-50-52 Edit Book Information “Book Information” ‹ Le paysage et son double — Pressbooks](https://user-images.githubusercontent.com/35763563/233329986-c4203fac-e3a1-4b4f-85b5-e25e31ac0244.png)

And in debug.log i got this
```
PHP Fatal error:  Uncaught TypeError: Pressbooks\Book::removeInvalidatedBisacCodes(): Argument #2 ($book_information_array) must be of type array, bool given, called in /var/www/html/wordpress/wp-content/plugins/pressbooks/inc/class-book.php on line 254 and defined in /var/www/html/wordpress/wp-content/plugins/pressbooks/inc/class-book.php:270
Stack trace:
#0 /var/www/html/wordpress/wp-content/plugins/pressbooks/inc/class-book.php(254): Pressbooks\Book::removeInvalidatedBisacCodes()
#1 /var/www/html/wordpress/wp-includes/class-wp-hook.php(308): Pressbooks\Book::notifyBisacCodesRemoved()
#2 /var/www/html/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#3 /var/www/html/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /var/www/html/wordpress/wp-admin/edit-form-advanced.php(500): do_action()
#5 /var/www/html/wordpress/wp-admin/post.php(206): require('...')
#6 {main}
  thrown in /var/www/html/wordpress/wp-content/plugins/pressbooks/inc/class-book.php on line 270
```

### Some debug already done
i've dump those var : $book_data_collector, $blog_id, $book_information_array, BookDataCollector::BOOK_INFORMATION_ARRAY 
```
static function notifyBisacCodesRemoved() {
		global $blog_id;
		$book_data_collector = BookDataCollector::init();
		$book_information_array = $book_data_collector->get( $blog_id, BookDataCollector::BOOK_INFORMATION_ARRAY );

		dump($book_data_collector, $blog_id, $book_information_array, BookDataCollector::BOOK_INFORMATION_ARRAY );
		
		if ( self::removeInvalidatedBisacCodes( $blog_id, $book_information_array ) ) {
			add_error( __(
				"This book was using a <a href='https://bisg.org/page/InactivatedCodes' target='_blank'> retired BISAC subject term </a>, which has been replaced in your book with a recommended BISAC replacement. You may wish to check the BISAC subject terms manually to confirm that you are satisfied with these replacements."
			) );
			return true;
		}
		return false;
	}
```
And dump results are 
```
^ Pressbooks\DataCollector\Book {#792}
^ 8
^ false
^ "pb_book_information_array"
```

### System Information
![Screenshot 2023-04-17 at 11-18-41 Diagnostics ‹ Bienvenue sur e-publish — Pressbooks2](https://user-images.githubusercontent.com/35763563/233330210-42ec3310-c090-4897-99b0-2899d0fcf255.png)

**Comment by richard015ar** [comment]
Thank you @SylDanh for reporting and debugging this.
It seems that you might have some invalid/deprecated bisac code in that book. Nevertheless, it should not throw and display errors.

I'm sending a fix for this. 

I appreciate your contribution, 
kind regards.
